<?php
/**
 * Theme functions and definitions.
 * This child theme was generated by Merlin WP.
 *
 * @link https://developer.wordpress.org/themes/basics/theme-functions/
 */

/*
 * If your child theme has more than one .css file (eg. ie.css, style.css, main.css) then
 * you will have to make sure to maintain all of the parent theme dependencies.
 *
 * Make sure you're using the correct handle for loading the parent theme's styles.
 * Failure to use the proper tag will result in a CSS file needlessly being loaded twice.
 * This will usually not affect the site appearance, but it's inefficient and extends your page's loading time.
 *
 * @link https://developer.wordpress.org/themes/advanced-topics/child-themes/
 */
function buddyx_child_enqueue_styles() {
	wp_enqueue_style( 'buddyx-style', get_template_directory_uri() . '/style.css' );
	wp_enqueue_style(
		'buddyx-child-style',
		get_stylesheet_directory_uri() . '/style.css?' . time(),
		array( 'buddyx-style' ),
		wp_get_theme()->get( 'Version' )
	);
}

add_action( 'wp_enqueue_scripts', 'buddyx_child_enqueue_styles' );

if ( get_stylesheet() !== get_template() ) {
	add_filter(
		'pre_update_option_theme_mods_' . get_stylesheet(),
		function ( $value, $old_value ) {
			update_option( 'theme_mods_' . get_template(), $value );
			return $old_value; // prevent update to child theme mods.
		},
		10,
		2
	);
	add_filter(
		'pre_option_theme_mods_' . get_stylesheet(),
		function (
			$default_values
		) {
			return get_option( 'theme_mods_' . get_template(), $default_values );
		}
	);
}

/*
 * ---------------------------------------------------------------------------
 * MIGRATED TO THE PLUGIN — 2026-09-05
 *
 * Roughly 600 lines of non-theme logic used to live below this point: username
 * hashing at registration, login and logout redirects, BuddyPress wording and
 * navigation, the members-directory gender filter, a custom xProfile date field,
 * and a profile-completion helper. None of it was theme work, and keeping it
 * here meant it was invisible to version control and would vanish if the theme
 * were ever switched.
 *
 * It now lives in the cashaadi-ui plugin:
 *   includes/modules/theme-compat/ThemeCompat.php   hooks, redirects, wording,
 *                                                    navigation, directory filter
 *   includes/modules/theme-compat/Datebox.php        the custom date field
 *   includes/core/globals.php                        csm_user_profile_is_complete()
 *
 * Deleted rather than moved: cashaadi_friends_screen_notification_settings(),
 * which the plugin's Engagement module had already unhooked — it governed two
 * email switches that no longer exist.
 *
 * WHAT REMAINS ABOVE is genuine theme work: the stylesheet enqueue and the
 * parent/child theme_mods bridge. The five BuddyPress template overrides in
 * buddypress/ also stay — templates belong to a theme.
 *
 * The previous file is kept alongside as functions.php.bak-premigration-*.
 * ---------------------------------------------------------------------------
 */

/**
 * Profile completion, still needed by the theme's own BuddyPress templates.
 *
 * members-loop.php and the friends templates call csm_user_profile_is_complete()
 * directly, so the theme cannot rely on the plugin being active to avoid a fatal.
 *
 * The plugin defines csm_user_profile_is_complete() (in core/globals.php) but
 * NOT cashaadi_has_missing_required_fields() — its version delegates to this one
 * when it exists. So this is not a duplicate: it is the only definition of the
 * required-field check, kept here because the theme's own templates need it and
 * both are function_exists-guarded, so whichever loads first wins and they agree.
 */
if ( ! function_exists( 'cashaadi_has_missing_required_fields' ) ) {
	function cashaadi_has_missing_required_fields( $user_id ) {
		if ( ! $user_id || ! function_exists( 'bp_xprofile_get_groups' ) ) {
			return false;
		}
		if ( function_exists( 'bp_get_user_has_avatar' ) && ! bp_get_user_has_avatar( $user_id ) ) {
			return true; // a profile photo is part of completion
		}
		$groups = bp_xprofile_get_groups( array(
			'fetch_fields'      => true,
			'fetch_field_data'  => false,
			'hide_empty_fields' => false,
		) );
		foreach ( $groups as $group ) {
			if ( empty( $group->fields ) ) {
				continue;
			}
			foreach ( $group->fields as $field ) {
				if ( empty( $field->is_required ) ) {
					continue; // only required fields gate anything
				}
				$value = xprofile_get_field_data( $field->id, $user_id );
				if ( '' === $value || null === $value || ( is_array( $value ) && 0 === count( $value ) ) ) {
					return true;
				}
			}
		}
		return false;
	}
}

if ( ! function_exists( 'csm_user_profile_is_complete' ) ) {
	function csm_user_profile_is_complete( $user_id = 0 ) {
		if ( ! $user_id ) {
			$user_id = get_current_user_id();
		}
		if ( ! $user_id ) {
			return false;
		}
		if ( function_exists( 'cashaadi_has_missing_required_fields' ) ) {
			return ! cashaadi_has_missing_required_fields( $user_id );
		}
		return true;
	}
}
