<?php
/**
 * Theme functions and definitions.
 * This child theme was generated by Merlin WP.
 *
 * @link https://developer.wordpress.org/themes/basics/theme-functions/
 */

/*
 * If your child theme has more than one .css file (eg. ie.css, style.css, main.css) then
 * you will have to make sure to maintain all of the parent theme dependencies.
 *
 * Make sure you're using the correct handle for loading the parent theme's styles.
 * Failure to use the proper tag will result in a CSS file needlessly being loaded twice.
 * This will usually not affect the site appearance, but it's inefficient and extends your page's loading time.
 *
 * @link https://developer.wordpress.org/themes/advanced-topics/child-themes/
 */
function buddyx_child_enqueue_styles() {
	wp_enqueue_style( 'buddyx-style', get_template_directory_uri() . '/style.css' );
	wp_enqueue_style(
		'buddyx-child-style',
		get_stylesheet_directory_uri() . '/style.css?' . time(),
		array( 'buddyx-style' ),
		wp_get_theme()->get( 'Version' )
	);
}

add_action( 'wp_enqueue_scripts', 'buddyx_child_enqueue_styles' );

if ( get_stylesheet() !== get_template() ) {
	add_filter(
		'pre_update_option_theme_mods_' . get_stylesheet(),
		function ( $value, $old_value ) {
			update_option( 'theme_mods_' . get_template(), $value );
			return $old_value; // prevent update to child theme mods.
		},
		10,
		2
	);
	add_filter(
		'pre_option_theme_mods_' . get_stylesheet(),
		function (
			$default_values
		) {
			return get_option( 'theme_mods_' . get_template(), $default_values );
		}
	);
}

function filter_bp_title_parts_for_registration_page( $ary_page_titles ) {
	if( bp_is_register_page() && !bp_get_membership_requests_required() ) {
		$ary_page_titles = ['Create Your CAShaadi Account'];
	}

	return $ary_page_titles;
}

add_filter('bp_get_title_parts', 'filter_bp_title_parts_for_registration_page');

function change_field_required_sign_from_text_to_symbol( $required_text, $field_id ) {
	return '*';
}

add_filter( 'bp_get_the_profile_field_required_label', 'change_field_required_sign_from_text_to_symbol', 10, 2 );

function rename_register_page_submit_button_text( $array_button_textes ) {
	$array_button_textes['register']['attributes']['value'] = 'Continue';

	return $array_button_textes;
}

add_filter( 'bp_nouveau_get_submit_button', 'rename_register_page_submit_button_text' );

function filter_buddypress_template_notices_for_register_page( $ary_messages ) {
	unset( $ary_messages['request-details'] );
	return $ary_messages;
}

add_filter('bp_nouveau_feedback_messages', 'filter_buddypress_template_notices_for_register_page');

// Deterministic, anonymized username: salted SHA-256 hash of the email.
// Set at user-insert time via wp_pre_insert_user_data so WordPress writes the
// exact value with no slug-uniqueness suffix (-2). One mechanism, at the source.
add_filter( 'wp_pre_insert_user_data', 'cashaadi_set_hashed_username', 10, 4 );
function cashaadi_set_hashed_username( $data, $update, $user_id, $userdata ) {

	// Only act on brand-new user creation, never on profile updates or existing users.
	if ( $update ) {
		return $data;
	}

	// Require an email to derive the deterministic slug; otherwise leave WP defaults.
	if ( empty( $data['user_email'] ) ) {
		return $data;
	}

	// Same email always yields the same handle; salted so it is not a plain email hash.
	$hash   = substr( hash( 'sha256', strtolower( trim( $data['user_email'] ) ) . wp_salt() ), 0, 12 );
	$handle = 'user_' . $hash;

	$data['user_login']    = $handle;
	$data['user_nicename'] = $handle;

	return $data;
}
/*
    Redirect user to edit profile page if profile is incomplete
    default to view profile page
*/
function cashaadi_check_user_profile_completion_and_redirect( $redirect_to, $user ) {
    
    // Only for valid users
    if (in_array('administrator', $user->roles)) {

    } else {
        if ( ! is_wp_error( $user ) && function_exists( 'bp_is_active' ) && bp_is_active( 'xprofile' ) ) {
            $user_id = $user->ID;

            // Get required fields
            /*$required_fields = bp_xprofile_get_groups( array( 'fetch_fields' => true ) );

            $incomplete = false;

            if ( ! empty( $required_fields ) ) {
                foreach ( $required_fields as $group ) {
                    foreach ( $group->fields as $field ) {
                        if ( $field->is_required ) {
                            $value = xprofile_get_field_data( $field->id, $user_id );
                            if ( empty( $value ) ) {
                                $incomplete = true;
                                break 2; // Exit both loops if one required field is empty
                            }
                        }
                    }
                }
            }*/
            
            $has_cur_user_profile_incomplete = ! csm_user_profile_is_complete( $user_id );
            
            $redirect_to = bp_core_get_user_domain( $user_id ); // default view profile page
            
            // If profile is incomplete, redirect to edit profile
            if( $has_cur_user_profile_incomplete ) {
                $redirect_to = bp_core_get_user_domain( $user_id ) . 'profile/edit/';
            }
        }
    }

    return $redirect_to;
}
add_filter( 'woocommerce_login_redirect', 'cashaadi_check_user_profile_completion_and_redirect', 10, 2 );

// logout to homepage
function cashaadi_redirect_after_logout() {
    wp_safe_redirect( home_url() );
    exit;
}
add_action( 'wp_logout', 'cashaadi_redirect_after_logout' );

function cashaadi_rename_loading_friends_to_matches( $ary_feedback_messages ) {

    if( isset( $ary_feedback_messages['message'] ) && $ary_feedback_messages['message'] === 'Loading your friends. Please wait.' ) {
        $ary_feedback_messages['message'] = 'Loading your matches. Please wait.';
    }
    if( isset( $ary_feedback_messages['message'] ) && $ary_feedback_messages['message'] === 'You have no pending friendship requests.' ) {
        $ary_feedback_messages['message'] = 'You have no pending match requests.';
    }

    if( isset( $ary_feedback_messages['message'] ) && $ary_feedback_messages['message'] === 'Sorry, no members were found.' ) {
        $ary_feedback_messages['message'] = 'Sorry, no matches were found.';
    }

    return $ary_feedback_messages;
}
add_filter('bp_nouveau_get_user_feedback', 'cashaadi_rename_loading_friends_to_matches');

function exclude_admins_and_current_loggedin_user_from_members_directory( $args ) {
    if ( bp_is_members_directory() ) {
        $exclude_ids = array();

        // Exclude administrators
        $admin_users = get_users( array(
            'role'   => 'Administrator',
            'fields' => 'ID'
        ) );
        if ( ! empty( $admin_users ) ) {
            $exclude_ids = array_merge( $exclude_ids, $admin_users );
        }

        // Exclude currently logged-in user
        if ( is_user_logged_in() ) {
            $exclude_ids[] = get_current_user_id();
        }

        // Merge with existing exclude array if necessary
        if ( ! empty( $exclude_ids ) ) {
            $args['exclude'] = ! empty( $args['exclude'] )
                ? array_merge( (array) $args['exclude'], $exclude_ids )
                : $exclude_ids;
        }
    }
    return $args;
}
add_filter( 'bp_after_has_members_parse_args', 'exclude_admins_and_current_loggedin_user_from_members_directory' );

/**
 * Members Directory filter
 * – hide admins + self
 * – show only opposite‑gender members for non‑admin users
 *
 * Works on bp_pre_user_query_construct which lets us
 * change the underlying BP_User_Query before it runs.
 */
add_action( 'bp_pre_user_query_construct', function ( BP_User_Query $query ) {
    
	/* -------------------------------------------------------------
	 * 0. Run only on the main Members directory
	 * ----------------------------------------------------------- */
	if ( ! bp_is_members_directory() ) {
		return;                       // widgets / profile tabs etc. unaffected
	}
	
	/* -------------------------------------------------------------
	 * 1. Always exclude admins and the current visitor
	 * ----------------------------------------------------------- */
	$exclude = isset( $query->query_vars['exclude'] )
		? (array) $query->query_vars['exclude']
		: array();

	// a) administrators
	$admin_ids = get_users( array(
		'role'   => 'administrator',
		'fields' => 'ids',
	) );
	$exclude = array_merge( $exclude, $admin_ids );

	// b) the logged‑in user (if any)
	if ( is_user_logged_in() ) {
		$exclude[] = bp_loggedin_user_id();
	}

	$query->query_vars['exclude'] = array_unique( array_map( 'intval', $exclude ) );


	/* -------------------------------------------------------------
	 * 2. Opposite‑gender filter (skip for admins & guests)
	 * ----------------------------------------------------------- */
	if ( ! is_user_logged_in() || current_user_can( 'administrator' ) ) {
		return;                       // no gender filter for admins/guests
	}
	
	$has_cur_user_profile_incomplete = ! csm_user_profile_is_complete( get_current_user_id() );
    if( $has_cur_user_profile_incomplete ) {
        // if current logged in user profile is incomplete then show all members on directory page
        return;   
    }
	
	// 2.1 get the visitor’s gender
	$current_gender = xprofile_get_field_data( 'Gender', bp_loggedin_user_id() );
	
	if ( ! $current_gender ) {
		return;                       // gender not set ➜ show everyone
	}

	$current_gender = strtolower( $current_gender );
	$want_gender = '';
	if( 'male' === $current_gender ) {
	    $want_gender = 'Female';
	} else if( 'female' === $current_gender ) {
	    $want_gender = 'Male';
	}

	if ( ! $want_gender ) {
		return;                       // unknown value ➜ show everyone
	}

	// 2.2 add an xprofile_query clause
	$xprofile_query   = $query->query_vars['xprofile_query'] ?? array();
	$xprofile_query[] = array(
		'field'   => 'Gender',       // use field *name* or numeric ID
		'value'   => $want_gender,
		'compare' => '=',
	);

	$query->query_vars['xprofile_query'] = $xprofile_query;
}, 20 );


// Only a user can view His/Her friends list
function cashaadi_hide_friends_if_not_self() {
 
    if ( bp_is_my_profile() || is_super_admin() )
        return;
 
    bp_core_remove_nav_item( 'friends' );
}
add_action( 'bp_friends_setup_nav', 'cashaadi_hide_friends_if_not_self' );

function cashaadi_register_custom_datebox() {

	if ( ! class_exists( 'BP_XProfile_Field_Type_Datebox' ) ) {
		return; // BuddyPress not active or xProfile component disabled
	}

	/**
	 * Our replacement class – inherits everything except the output.
	 */
	class My_Custom_Datebox_Field extends BP_XProfile_Field_Type_Datebox {

		public function __construct() {
			parent::__construct();

			// Change the label that appears in wp-admin › Users › Profile Fields.
			$this->name     = __( 'Date (picker)', 'mytext' );
			$this->category = __( 'Custom', 'mytext' );
		}

		/**
		 * Override the three-select markup with a single <input type="date">.
		 */
		public function edit_field_html( array $raw_properties = array() ) {

            // -------------------------------------------------------------
            // 1. Figure out whose profile we’re editing.
            // -------------------------------------------------------------
            if ( isset( $raw_properties['user_id'] ) ) {
                $user_id = (int) $raw_properties['user_id'];
                unset( $raw_properties['user_id'] );
            } else {
                $user_id = bp_displayed_user_id();
            }

            // -------------------------------------------------------------
            // 2. Build the attribute arrays for each <select>.
            // -------------------------------------------------------------
            $day_r = bp_parse_args(
                $raw_properties,
                array(
                    'id'   => bp_get_the_profile_field_input_name() . '_day',
                    'name' => bp_get_the_profile_field_input_name() . '_day',
                )
            );

            $month_r = bp_parse_args(
                $raw_properties,
                array(
                    'id'   => bp_get_the_profile_field_input_name() . '_month',
                    'name' => bp_get_the_profile_field_input_name() . '_month',
                )
            );

            $year_r = bp_parse_args(
                $raw_properties,
                array(
                    'id'   => bp_get_the_profile_field_input_name() . '_year',
                    'name' => bp_get_the_profile_field_input_name() . '_year',
                )
            );
            ?>

                <legend>
                    <?php bp_the_profile_field_name(); ?>
                    <?php bp_the_profile_field_required_label(); ?>
                </legend>

                <?php if ( bp_get_the_profile_field_description() ) : ?>
                    <p class="description" tabindex="0"><?php bp_the_profile_field_description(); ?></p>
                <?php endif; ?>

                <div class="input-options datebox-selects">
                    <?php
                    /**
                     * Print validation errors, if any.
                     * Hook name is dynamic (eg. bp_field_12_errors).
                     */
                    do_action( bp_get_the_profile_field_errors_action() );
                    ?>

                    <!-- Day ------------------------------------------------- -->
                    <div class="datebox-field datebox-day">
                        <label for="<?php bp_the_profile_field_input_name(); ?>_day" class="xprofile-field-label">
                            <?php esc_html_e( 'Day', 'buddypress' ); ?>
                        </label>

                        <select <?php $this->output_edit_field_html_elements( $day_r ); ?>>
                            <?php bp_the_profile_field_options( array(
                                'type'    => 'day',
                                'user_id' => $user_id,
                            ) ); ?>
                        </select>
                    </div>

                    <!-- Month ----------------------------------------------- -->
                    <div class="datebox-field datebox-month">
                        <label for="<?php bp_the_profile_field_input_name(); ?>_month" class="xprofile-field-label">
                            <?php esc_html_e( 'Month', 'buddypress' ); ?>
                        </label>

                        <select <?php $this->output_edit_field_html_elements( $month_r ); ?>>
                            <?php bp_the_profile_field_options( array(
                                'type'    => 'month',
                                'user_id' => $user_id,
                            ) ); ?>
                        </select>
                    </div>

                    <!-- Year ------------------------------------------------ -->
                    <div class="datebox-field datebox-year">
                        <label for="<?php bp_the_profile_field_input_name(); ?>_year" class="xprofile-field-label">
                            <?php esc_html_e( 'Year', 'buddypress' ); ?>
                        </label>

                        <select <?php $this->output_edit_field_html_elements( $year_r ); ?>>
                            <?php bp_the_profile_field_options( array(
                                'type'    => 'year',
                                'user_id' => $user_id,
                            ) ); ?>
                        </select>
                    </div>

                </div><!-- .input-options.datebox-selects -->

        <?php
        }

	}

	/*
	 *  Tell BP to use our class **instead** of the core one
	 *  whenever a field is saved as “Date”.
	 */
	add_filter(
		'bp_xprofile_get_field_types',
		function ( $types ) {
			$types['datebox'] = 'My_Custom_Datebox_Field'; // drop‐in replacement
			return $types;
		}
	);
}

add_action( 'bp_init', 'cashaadi_register_custom_datebox', 20 );

function cashaadi_rename_friend_with_match( $button_args ) {
    if( isset( $button_args['link_text'] ) && $button_args['link_text'] == 'Add Friend' ) {
        $button_args['link_text'] = 'Add Match';
        $button_args['link_title'] = 'Add Match';
    }
    
    if( isset( $button_args['link_text'] ) && $button_args['link_text'] == 'Cancel Friendship Request' ) {
        $button_args['link_text'] = 'Cancel Match Request';
        $button_args['link_title'] = 'Cancel Match Requested';
    }
    
    if( isset( $button_args['link_text'] ) && $button_args['link_text'] == 'Friendship Requested' ) {
        $button_args['link_text'] = 'Match Request Sent';
        $button_args['link_title'] = 'Match Request Sent';
    }
    
    if( isset( $button_args['link_text'] ) && $button_args['link_text'] == 'Cancel Friendship' ) {
        $button_args['link_text'] = 'Withdraw Match Request';
        $button_args['link_title'] = 'Withdraw Match Request';
    }

    return $button_args;
}

add_filter('bp_get_add_friend_button', 'cashaadi_rename_friend_with_match');

remove_action( 'bp_notification_settings', 'friends_screen_notification_settings' );
add_action( 'bp_notification_settings', 'cashaadi_friends_screen_notification_settings' );
function cashaadi_friends_screen_notification_settings() {

	if ( ! $send_requests = bp_get_user_meta( bp_displayed_user_id(), 'notification_friends_friendship_request', true ) ) {
		$send_requests = 'yes';
	}

	if ( ! $accept_requests = bp_get_user_meta( bp_displayed_user_id(), 'notification_friends_friendship_accepted', true ) ) {
		$accept_requests = 'yes';
	}
	?>

	<table class="notification-settings" id="friends-notification-settings">
		<thead>
			<tr>
				<th class="icon"></th>
				<th class="title"><?php echo esc_html_x( 'Matches', 'Match settings on notification settings page', 'buddypress' ); ?></th>
				<th class="yes"><?php esc_html_e( 'Yes', 'buddypress' ); ?></th>
				<th class="no"><?php esc_html_e( 'No', 'buddypress' ); ?></th>
			</tr>
		</thead>

		<tbody>
			<tr id="friends-notification-settings-request">
				<td></td>
				<td><?php echo esc_html_x( 'A member sends you a match request', 'Friend settings on notification settings page', 'buddypress' ); ?></td>
				<td class="yes"><input type="radio" name="notifications[notification_friends_friendship_request]" id="notification-friends-friendship-request-yes" value="yes" <?php checked( $send_requests, 'yes', true ) ?>/><label for="notification-friends-friendship-request-yes" class="bp-screen-reader-text"><?php
					/* translators: accessibility text */
					esc_html_e( 'Yes, send email', 'buddypress' );
				?></label></td>
				<td class="no"><input type="radio" name="notifications[notification_friends_friendship_request]" id="notification-friends-friendship-request-no" value="no" <?php checked( $send_requests, 'no', true ) ?>/><label for="notification-friends-friendship-request-no" class="bp-screen-reader-text"><?php
					/* translators: accessibility text */
					esc_html_e( 'No, do not send email', 'buddypress' );
				?></label></td>
			</tr>
			<tr id="friends-notification-settings-accepted">
				<td></td>
				<td><?php echo esc_html_x( 'A member accepts your match request', 'Friend settings on notification settings page', 'buddypress' ) ?></td>
				<td class="yes"><input type="radio" name="notifications[notification_friends_friendship_accepted]" id="notification-friends-friendship-accepted-yes" value="yes" <?php checked( $accept_requests, 'yes', true ) ?>/><label for="notification-friends-friendship-accepted-yes" class="bp-screen-reader-text"><?php
					/* translators: accessibility text */
					esc_html_e( 'Yes, send email', 'buddypress' );
				?></label></td>
				<td class="no"><input type="radio" name="notifications[notification_friends_friendship_accepted]" id="notification-friends-friendship-accepted-no" value="no" <?php checked( $accept_requests, 'no', true ) ?>/><label for="notification-friends-friendship-accepted-no" class="bp-screen-reader-text"><?php
					/* translators: accessibility text */
					esc_html_e( 'No, do not send email', 'buddypress' );
				?></label></td>
			</tr>

			<?php

			/**
			 * Fires after the last table row on the friends notification screen.
			 *
			 * @since 1.0.0
			 */
			do_action( 'friends_screen_notification_settings' ); ?>

		</tbody>
	</table>

<?php
}

if ( ! function_exists( 'buddyx_render_member_cover_image' ) ) {

	if ( ! bp_disable_cover_image_uploads() ) {
		add_action( 'buddyx_before_member_avatar_member_directory', 'buddyx_render_member_cover_image', 10 );
	}

	function buddyx_render_member_cover_image() {
		$cover_img_url = bp_attachments_get_attachment(
			'url',
			$args      = array(
				'object_dir' => 'members',
				'item_id'    => $user_id = bp_get_member_user_id(),
				'type'       => 'cover-image',
			)
		);
		
		$default_members_cover = site_url('/wp-content/uploads/2023/11/CAshaadi-RGB-Square.png');
		$cover_img_url         = isset( $cover_img_url ) && !empty( $cover_img_url ) ? $cover_img_url : $default_members_cover;

		$default_class = '';
		if( $cover_img_url == $default_members_cover  ) {
		    $default_class = 'default';
		}
		
		echo '<div class="buddyx-mem-cover-wrapper"><div class="buddyx-mem-cover-img ' . $default_class . '"><img src="' . esc_url( $cover_img_url ) . '" /></div></div>';
	}

}

// if user has incomplete profile and trying to access the other user profile then redirect to current loggedin user to his/her profile instead of other user
// Returns true only if a REQUIRED xProfile field is empty for the given user.
// Gate logic is based on mandatory (required) fields only, NOT the display-only completion meter.
function cashaadi_has_missing_required_fields( $user_id ) {
    if ( ! $user_id || ! function_exists( 'bp_xprofile_get_groups' ) ) {
        return false;
    }
	// Require a profile photo (avatar) as part of completion.
	if ( function_exists( 'bp_get_user_has_avatar' ) && ! bp_get_user_has_avatar( $user_id ) ) {
		return true; // missing profile photo => incomplete
	}

    $groups = bp_xprofile_get_groups( array(
        'fetch_fields'      => true,
        'fetch_field_data'  => false,
        'hide_empty_fields' => false,
    ) );
    foreach ( $groups as $group ) {
        if ( empty( $group->fields ) ) {
            continue;
        }
        foreach ( $group->fields as $field ) {
            if ( empty( $field->is_required ) ) {
                continue; // only enforce required fields
            }
            $value = xprofile_get_field_data( $field->id, $user_id );
            if ( $value === '' || $value === null || ( is_array( $value ) && count( $value ) === 0 ) ) {
                return true; // a required field is empty -> incomplete
            }
        }
    }
    return false;
}

function hide_admin_bar_for_subscribers() {
    if ( current_user_can( 'subscriber' ) ) {
        show_admin_bar( false );
    }
}
add_action( 'after_setup_theme', 'hide_admin_bar_for_subscribers' );

function cashaadi_bp_rename_friends_tab() {
    global $bp;
    if ( isset( $bp->members->nav ) ) {
        $bp->members->nav->edit_nav(
            array( 'name' => 'Matches' ),
            'friends'
        );
        
        $bp->members->nav->edit_nav(
            array( 'name' => __( 'My Matches', 'buddypress' ) ),
            'my-friends',  // subnav slug
            'friends'      // parent nav slug
        );
        
        // remove "Export Data" feature from "Settings" tab
        bp_core_remove_subnav_item(
            'settings',   // Parent nav (Settings)
            'data'        // Subnav slug (Export Data)
        );
    }
}
add_action( 'bp_setup_nav', 'cashaadi_bp_rename_friends_tab', 100 );

/**
 * Flag: Hide exact "last active" time everywhere. Show only a coarse
 * "Active today" indicator (active within the last 24h) or nothing.
 * Profile headers use bp_get_last_activity; member loops use bp_member_last_active.
 */
function cashaadi_coarse_last_active( $string ) {
    $user_id = 0;
    if ( function_exists( 'bp_get_member_user_id' ) && bp_get_member_user_id() ) {
        $user_id = bp_get_member_user_id();
    } elseif ( function_exists( 'bp_displayed_user_id' ) && bp_displayed_user_id() ) {
        $user_id = bp_displayed_user_id();
    }
    if ( ! $user_id || ! function_exists( 'bp_get_user_last_activity' ) ) {
        return '';
    }
    $last = bp_get_user_last_activity( $user_id );
    if ( empty( $last ) ) {
        return '';
    }
    $ts = strtotime( $last );
    if ( $ts && ( time() - $ts ) < DAY_IN_SECONDS ) {
        return __( 'Active today', 'buddyx-child' );
    }
    return '';
}
add_filter( 'bp_get_last_activity', 'cashaadi_coarse_last_active', 99 );
add_filter( 'bp_member_last_active', 'cashaadi_coarse_last_active', 99 );
